# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'DemandaYCables.ui'
#
# Created by: PyQt5 UI code generator 5.15.11
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(1121, 847)
        MainWindow.setStyleSheet("QWidget {\n"
"    background-color: #383838;\n"
"    color: #FFFFFF;\n"
"}\n"
"\n"
"QPushButton {\n"
"    color: #FFFFFF;\n"
"}\n"
"\n"
"QPushButton:hover {\n"
"    background-color: #5E5E5E;\n"
"}\n"
"\n"
"QLineEdit {\n"
"    background-color: #1E1E1E;\n"
"    color: #FFFFFF;\n"
"    border: 1px solid #FFFFFF;\n"
"}")
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.stackedWidget = QtWidgets.QStackedWidget(self.centralwidget)
        self.stackedWidget.setGeometry(QtCore.QRect(0, 0, 1121, 851))
        self.stackedWidget.setFrameShape(QtWidgets.QFrame.Box)
        self.stackedWidget.setFrameShadow(QtWidgets.QFrame.Plain)
        self.stackedWidget.setLineWidth(0)
        self.stackedWidget.setMidLineWidth(0)
        self.stackedWidget.setObjectName("stackedWidget")
        self.page_1 = QtWidgets.QWidget()
        self.page_1.setObjectName("page_1")
        self.label_titulo = QtWidgets.QLabel(self.page_1)
        self.label_titulo.setGeometry(QtCore.QRect(0, 10, 1121, 61))
        self.label_titulo.setStyleSheet("QLabel {\n"
"    font-size: 40px;\n"
"    color: #FFA726;\n"
"}")
        self.label_titulo.setAlignment(QtCore.Qt.AlignCenter)
        self.label_titulo.setObjectName("label_titulo")
        self.tableWidget = QtWidgets.QTableWidget(self.page_1)
        self.tableWidget.setGeometry(QtCore.QRect(60, 230, 901, 361))
        self.tableWidget.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.tableWidget.setStyleSheet("QTableWidget {\n"
"    gridline-color: #505050;\n"
"    color: #E0E0E0;\n"
"    font-size: 14px;\n"
"}\n"
"")
        self.tableWidget.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.tableWidget.setFrameShadow(QtWidgets.QFrame.Plain)
        self.tableWidget.setLineWidth(5)
        self.tableWidget.setMidLineWidth(5)
        self.tableWidget.setVerticalScrollBarPolicy(QtCore.Qt.ScrollBarAsNeeded)
        self.tableWidget.setSizeAdjustPolicy(QtWidgets.QAbstractScrollArea.AdjustIgnored)
        self.tableWidget.setAutoScrollMargin(16)
        self.tableWidget.setEditTriggers(QtWidgets.QAbstractItemView.AllEditTriggers)
        self.tableWidget.setTabKeyNavigation(True)
        self.tableWidget.setProperty("showDropIndicator", True)
        self.tableWidget.setSelectionMode(QtWidgets.QAbstractItemView.ExtendedSelection)
        self.tableWidget.setTextElideMode(QtCore.Qt.ElideMiddle)
        self.tableWidget.setShowGrid(True)
        self.tableWidget.setGridStyle(QtCore.Qt.SolidLine)
        self.tableWidget.setWordWrap(True)
        self.tableWidget.setCornerButtonEnabled(True)
        self.tableWidget.setRowCount(8)
        self.tableWidget.setColumnCount(5)
        self.tableWidget.setObjectName("tableWidget")
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setItem(0, 0, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setItem(0, 1, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setItem(0, 2, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setItem(0, 3, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setItem(0, 4, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setItem(1, 0, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setItem(2, 0, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setItem(2, 1, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setItem(3, 0, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setItem(3, 1, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setItem(4, 0, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setItem(5, 0, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setItem(6, 0, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setItem(7, 0, item)
        self.tableWidget.horizontalHeader().setVisible(False)
        self.tableWidget.horizontalHeader().setCascadingSectionResizes(False)
        self.tableWidget.horizontalHeader().setDefaultSectionSize(159)
        self.tableWidget.horizontalHeader().setHighlightSections(False)
        self.tableWidget.horizontalHeader().setMinimumSectionSize(44)
        self.tableWidget.verticalHeader().setVisible(False)
        self.tableWidget.verticalHeader().setDefaultSectionSize(44)
        self.tableWidget.verticalHeader().setHighlightSections(False)
        self.tableWidget.verticalHeader().setMinimumSectionSize(47)
        self.label_enunciado = QtWidgets.QLabel(self.page_1)
        self.label_enunciado.setGeometry(QtCore.QRect(60, 140, 431, 31))
        self.label_enunciado.setStyleSheet("QLabel {\n"
"    font-size: 20px;\n"
"}")
        self.label_enunciado.setObjectName("label_enunciado")
        self.label_potenciaInsIluminacion = QtWidgets.QLabel(self.page_1)
        self.label_potenciaInsIluminacion.setGeometry(QtCore.QRect(440, 670, 151, 31))
        self.label_potenciaInsIluminacion.setStyleSheet("QLabel {\n"
"    font-size: 20px;\n"
"}")
        self.label_potenciaInsIluminacion.setText("")
        self.label_potenciaInsIluminacion.setObjectName("label_potenciaInsIluminacion")
        self.label_potenciaInsTomas = QtWidgets.QLabel(self.page_1)
        self.label_potenciaInsTomas.setGeometry(QtCore.QRect(420, 710, 151, 31))
        self.label_potenciaInsTomas.setStyleSheet("QLabel {\n"
"    font-size: 20px;\n"
"}")
        self.label_potenciaInsTomas.setText("")
        self.label_potenciaInsTomas.setObjectName("label_potenciaInsTomas")
        self.label_titulo2 = QtWidgets.QLabel(self.page_1)
        self.label_titulo2.setGeometry(QtCore.QRect(80, 670, 351, 31))
        self.label_titulo2.setStyleSheet("QLabel {\n"
"    font-size: 20px;\n"
"    color: #FFD54F;\n"
"    font-weight: bold;\n"
"}")
        self.label_titulo2.setObjectName("label_titulo2")
        self.label_titulo3 = QtWidgets.QLabel(self.page_1)
        self.label_titulo3.setGeometry(QtCore.QRect(80, 710, 331, 31))
        self.label_titulo3.setStyleSheet("QLabel {\n"
"    font-size: 20px;\n"
"    color: #FFD54F;\n"
"    font-weight: bold;\n"
"}")
        self.label_titulo3.setObjectName("label_titulo3")
        self.pushButton_calcularDemandaCasa = QtWidgets.QPushButton(self.page_1)
        self.pushButton_calcularDemandaCasa.setGeometry(QtCore.QRect(400, 600, 241, 51))
        self.pushButton_calcularDemandaCasa.setStyleSheet("QPushButton {\n"
"    background-color: #FFA726; \n"
"    border-radius: 10px;\n"
"    font-size: 20px; \n"
"}\n"
"QPushButton:hover {\n"
"    background-color: #FF9800;\n"
"}")
        self.pushButton_calcularDemandaCasa.setObjectName("pushButton_calcularDemandaCasa")
        self.pushButton_calcularDemandaConjunto = QtWidgets.QPushButton(self.page_1)
        self.pushButton_calcularDemandaConjunto.setGeometry(QtCore.QRect(80, 770, 421, 51))
        self.pushButton_calcularDemandaConjunto.setStyleSheet("QPushButton {\n"
"    background-color: #e59866; \n"
"    border-radius: 10px;\n"
"    font-size: 20px;\n"
"    font-weight: bold; \n"
"}\n"
"QPushButton:hover {\n"
"    background-color: #dc7633;\n"
"}")
        self.pushButton_calcularDemandaConjunto.setObjectName("pushButton_calcularDemandaConjunto")
        self.pushButton_calcularCable = QtWidgets.QPushButton(self.page_1)
        self.pushButton_calcularCable.setGeometry(QtCore.QRect(610, 770, 361, 51))
        self.pushButton_calcularCable.setStyleSheet("QPushButton {\n"
"    background-color: #e59866; \n"
"    border-radius: 10px;\n"
"    font-size: 20px;\n"
"    font-weight: bold; \n"
"}\n"
"QPushButton:hover {\n"
"    background-color: #dc7633;\n"
"}")
        self.pushButton_calcularCable.setObjectName("pushButton_calcularCable")
        self.spinBox_numeroEspacios = QtWidgets.QSpinBox(self.page_1)
        self.spinBox_numeroEspacios.setGeometry(QtCore.QRect(500, 141, 71, 31))
        self.spinBox_numeroEspacios.setStyleSheet("QSpinBox {\n"
"    font-size: 20px;\n"
"    border: none;\n"
"    border-bottom: 1px solid white;\n"
"}")
        self.spinBox_numeroEspacios.setAlignment(QtCore.Qt.AlignCenter)
        self.spinBox_numeroEspacios.setMinimum(1)
        self.spinBox_numeroEspacios.setObjectName("spinBox_numeroEspacios")
        self.label_enunciado_2 = QtWidgets.QLabel(self.page_1)
        self.label_enunciado_2.setGeometry(QtCore.QRect(60, 190, 421, 31))
        self.label_enunciado_2.setStyleSheet("QLabel {\n"
"    font-size: 20px;\n"
"}")
        self.label_enunciado_2.setObjectName("label_enunciado_2")
        self.pushButton_generarTabla = QtWidgets.QPushButton(self.page_1)
        self.pushButton_generarTabla.setGeometry(QtCore.QRect(590, 140, 101, 41))
        self.pushButton_generarTabla.setStyleSheet("QPushButton {\n"
"    background-color: #FFA726; \n"
"    border-radius: 10px;\n"
"    font-size: 20px; \n"
"}\n"
"QPushButton:hover {\n"
"    background-color: #FF9800;\n"
"}")
        self.pushButton_generarTabla.setObjectName("pushButton_generarTabla")
        self.label_anchoCasa = QtWidgets.QLabel(self.page_1)
        self.label_anchoCasa.setGeometry(QtCore.QRect(60, 90, 161, 31))
        self.label_anchoCasa.setStyleSheet("QLabel {\n"
"    font-size: 20px;\n"
"}")
        self.label_anchoCasa.setObjectName("label_anchoCasa")
        self.label_largoCasa = QtWidgets.QLabel(self.page_1)
        self.label_largoCasa.setGeometry(QtCore.QRect(350, 90, 161, 31))
        self.label_largoCasa.setStyleSheet("QLabel {\n"
"    font-size: 20px;\n"
"}")
        self.label_largoCasa.setObjectName("label_largoCasa")
        self.label_numeroAires = QtWidgets.QLabel(self.page_1)
        self.label_numeroAires.setGeometry(QtCore.QRect(720, 80, 301, 31))
        self.label_numeroAires.setStyleSheet("QLabel {\n"
"    font-size: 20px;\n"
"}")
        self.label_numeroAires.setObjectName("label_numeroAires")
        self.label_titulo4 = QtWidgets.QLabel(self.page_1)
        self.label_titulo4.setGeometry(QtCore.QRect(660, 670, 201, 31))
        self.label_titulo4.setStyleSheet("QLabel {\n"
"    font-size: 20px;\n"
"    color: #FFD54F;\n"
"    font-weight: bold;\n"
"}")
        self.label_titulo4.setObjectName("label_titulo4")
        self.label_potenciaFuerza = QtWidgets.QLabel(self.page_1)
        self.label_potenciaFuerza.setGeometry(QtCore.QRect(870, 670, 151, 31))
        self.label_potenciaFuerza.setStyleSheet("QLabel {\n"
"    font-size: 20px;\n"
"}")
        self.label_potenciaFuerza.setText("")
        self.label_potenciaFuerza.setObjectName("label_potenciaFuerza")
        self.label_titulo5 = QtWidgets.QLabel(self.page_1)
        self.label_titulo5.setGeometry(QtCore.QRect(660, 710, 201, 31))
        self.label_titulo5.setStyleSheet("QLabel {\n"
"    font-size: 20px;\n"
"    color: #FFD54F;\n"
"    font-weight: bold;\n"
"}")
        self.label_titulo5.setObjectName("label_titulo5")
        self.label_demandaMaxima = QtWidgets.QLabel(self.page_1)
        self.label_demandaMaxima.setGeometry(QtCore.QRect(870, 710, 151, 31))
        self.label_demandaMaxima.setStyleSheet("QLabel {\n"
"    font-size: 20px;\n"
"}")
        self.label_demandaMaxima.setText("")
        self.label_demandaMaxima.setObjectName("label_demandaMaxima")
        self.lineEdit_anchoCasa = QtWidgets.QLineEdit(self.page_1)
        self.lineEdit_anchoCasa.setGeometry(QtCore.QRect(220, 90, 71, 31))
        self.lineEdit_anchoCasa.setStyleSheet("QLineEdit {\n"
"    border: none;\n"
"    border-bottom: 2px solid white;\n"
"    background-color: transparent;\n"
"    font-size: 23px;\n"
"}\n"
"QLineEdit:hover {\n"
"    background-color: #4d4d4d;\n"
"}")
        self.lineEdit_anchoCasa.setText("")
        self.lineEdit_anchoCasa.setAlignment(QtCore.Qt.AlignCenter)
        self.lineEdit_anchoCasa.setObjectName("lineEdit_anchoCasa")
        self.lineEdit_largoCasa = QtWidgets.QLineEdit(self.page_1)
        self.lineEdit_largoCasa.setGeometry(QtCore.QRect(510, 90, 71, 31))
        self.lineEdit_largoCasa.setStyleSheet("QLineEdit {\n"
"    border: none;\n"
"    border-bottom: 2px solid white;\n"
"    background-color: transparent;\n"
"    font-size: 23px;\n"
"}\n"
"QLineEdit:hover {\n"
"    background-color: #4d4d4d;\n"
"}")
        self.lineEdit_largoCasa.setText("")
        self.lineEdit_largoCasa.setAlignment(QtCore.Qt.AlignCenter)
        self.lineEdit_largoCasa.setObjectName("lineEdit_largoCasa")
        self.lineEdit_numeroAires = QtWidgets.QLineEdit(self.page_1)
        self.lineEdit_numeroAires.setGeometry(QtCore.QRect(1020, 80, 71, 31))
        self.lineEdit_numeroAires.setStyleSheet("QLineEdit {\n"
"    border: none;\n"
"    border-bottom: 2px solid white;\n"
"    background-color: transparent;\n"
"    font-size: 23px;\n"
"}\n"
"QLineEdit:hover {\n"
"    background-color: #4d4d4d;\n"
"}")
        self.lineEdit_numeroAires.setText("")
        self.lineEdit_numeroAires.setAlignment(QtCore.Qt.AlignCenter)
        self.lineEdit_numeroAires.setObjectName("lineEdit_numeroAires")
        self.label_potenciaAire = QtWidgets.QLabel(self.page_1)
        self.label_potenciaAire.setGeometry(QtCore.QRect(720, 130, 301, 31))
        self.label_potenciaAire.setStyleSheet("QLabel {\n"
"    font-size: 20px;\n"
"}")
        self.label_potenciaAire.setObjectName("label_potenciaAire")
        self.lineEdit_potenciaAire = QtWidgets.QLineEdit(self.page_1)
        self.lineEdit_potenciaAire.setGeometry(QtCore.QRect(1020, 130, 71, 31))
        self.lineEdit_potenciaAire.setStyleSheet("QLineEdit {\n"
"    border: none;\n"
"    border-bottom: 2px solid white;\n"
"    background-color: transparent;\n"
"    font-size: 23px;\n"
"}\n"
"QLineEdit:hover {\n"
"    background-color: #4d4d4d;\n"
"}")
        self.lineEdit_potenciaAire.setText("")
        self.lineEdit_potenciaAire.setAlignment(QtCore.Qt.AlignCenter)
        self.lineEdit_potenciaAire.setObjectName("lineEdit_potenciaAire")
        self.stackedWidget.addWidget(self.page_1)
        self.page_2 = QtWidgets.QWidget()
        self.page_2.setObjectName("page_2")
        self.label_tituloDemandaConjunto = QtWidgets.QLabel(self.page_2)
        self.label_tituloDemandaConjunto.setGeometry(QtCore.QRect(0, 70, 1121, 61))
        self.label_tituloDemandaConjunto.setStyleSheet("QLabel {\n"
"    font-size: 40px;\n"
"    color: #FFA726;\n"
"}")
        self.label_tituloDemandaConjunto.setAlignment(QtCore.Qt.AlignCenter)
        self.label_tituloDemandaConjunto.setObjectName("label_tituloDemandaConjunto")
        self.label_numeroCasas = QtWidgets.QLabel(self.page_2)
        self.label_numeroCasas.setGeometry(QtCore.QRect(100, 250, 291, 31))
        self.label_numeroCasas.setStyleSheet("QLabel {\n"
"    font-size: 20px;\n"
"}")
        self.label_numeroCasas.setObjectName("label_numeroCasas")
        self.lineEdit_numeroCasas = QtWidgets.QLineEdit(self.page_2)
        self.lineEdit_numeroCasas.setGeometry(QtCore.QRect(410, 250, 91, 31))
        self.lineEdit_numeroCasas.setStyleSheet("QLineEdit {\n"
"    border: none;\n"
"    border-bottom: 2px solid white;\n"
"    background-color: transparent;\n"
"    font-size: 23px;\n"
"}\n"
"QLineEdit:hover {\n"
"    background-color: #4d4d4d;\n"
"}")
        self.lineEdit_numeroCasas.setText("")
        self.lineEdit_numeroCasas.setAlignment(QtCore.Qt.AlignCenter)
        self.lineEdit_numeroCasas.setObjectName("lineEdit_numeroCasas")
        self.lineEdit_numeroLocales = QtWidgets.QLineEdit(self.page_2)
        self.lineEdit_numeroLocales.setGeometry(QtCore.QRect(410, 320, 91, 31))
        self.lineEdit_numeroLocales.setStyleSheet("QLineEdit {\n"
"    border: none;\n"
"    border-bottom: 2px solid white;\n"
"    background-color: transparent;\n"
"    font-size: 23px;\n"
"}\n"
"QLineEdit:hover {\n"
"    background-color: #4d4d4d;\n"
"}")
        self.lineEdit_numeroLocales.setText("")
        self.lineEdit_numeroLocales.setAlignment(QtCore.Qt.AlignCenter)
        self.lineEdit_numeroLocales.setObjectName("lineEdit_numeroLocales")
        self.label_numeroLocales = QtWidgets.QLabel(self.page_2)
        self.label_numeroLocales.setGeometry(QtCore.QRect(100, 320, 301, 31))
        self.label_numeroLocales.setStyleSheet("QLabel {\n"
"    font-size: 20px;\n"
"}")
        self.label_numeroLocales.setObjectName("label_numeroLocales")
        self.label_demandaMaxLocal = QtWidgets.QLabel(self.page_2)
        self.label_demandaMaxLocal.setGeometry(QtCore.QRect(100, 390, 311, 31))
        self.label_demandaMaxLocal.setStyleSheet("QLabel {\n"
"    font-size: 20px;\n"
"}")
        self.label_demandaMaxLocal.setObjectName("label_demandaMaxLocal")
        self.lineEdit_demandaMaxLocal = QtWidgets.QLineEdit(self.page_2)
        self.lineEdit_demandaMaxLocal.setGeometry(QtCore.QRect(410, 390, 91, 31))
        self.lineEdit_demandaMaxLocal.setStyleSheet("QLineEdit {\n"
"    border: none;\n"
"    border-bottom: 2px solid white;\n"
"    background-color: transparent;\n"
"    font-size: 23px;\n"
"}\n"
"QLineEdit:hover {\n"
"    background-color: #4d4d4d;\n"
"}")
        self.lineEdit_demandaMaxLocal.setText("")
        self.lineEdit_demandaMaxLocal.setAlignment(QtCore.Qt.AlignCenter)
        self.lineEdit_demandaMaxLocal.setObjectName("lineEdit_demandaMaxLocal")
        self.lineEdit_demandaMaxServicios = QtWidgets.QLineEdit(self.page_2)
        self.lineEdit_demandaMaxServicios.setGeometry(QtCore.QRect(520, 460, 91, 31))
        self.lineEdit_demandaMaxServicios.setStyleSheet("QLineEdit {\n"
"    border: none;\n"
"    border-bottom: 2px solid white;\n"
"    background-color: transparent;\n"
"    font-size: 23px;\n"
"}\n"
"QLineEdit:hover {\n"
"    background-color: #4d4d4d;\n"
"}")
        self.lineEdit_demandaMaxServicios.setText("")
        self.lineEdit_demandaMaxServicios.setAlignment(QtCore.Qt.AlignCenter)
        self.lineEdit_demandaMaxServicios.setObjectName("lineEdit_demandaMaxServicios")
        self.label_demandaMaxServicios = QtWidgets.QLabel(self.page_2)
        self.label_demandaMaxServicios.setGeometry(QtCore.QRect(100, 460, 411, 31))
        self.label_demandaMaxServicios.setStyleSheet("QLabel {\n"
"    font-size: 20px;\n"
"}")
        self.label_demandaMaxServicios.setObjectName("label_demandaMaxServicios")
        self.label_demandaMaxConjunto = QtWidgets.QLabel(self.page_2)
        self.label_demandaMaxConjunto.setGeometry(QtCore.QRect(600, 670, 151, 31))
        self.label_demandaMaxConjunto.setStyleSheet("QLabel {\n"
"    font-size: 20px;\n"
"}")
        self.label_demandaMaxConjunto.setText("")
        self.label_demandaMaxConjunto.setObjectName("label_demandaMaxConjunto")
        self.label_titulo_demandaMaxConjunto = QtWidgets.QLabel(self.page_2)
        self.label_titulo_demandaMaxConjunto.setGeometry(QtCore.QRect(260, 670, 331, 31))
        self.label_titulo_demandaMaxConjunto.setStyleSheet("QLabel {\n"
"    font-size: 20px;\n"
"    color: #FFD54F;\n"
"    font-weight: bold;\n"
"}")
        self.label_titulo_demandaMaxConjunto.setObjectName("label_titulo_demandaMaxConjunto")
        self.pushButton_calcularDemandaMaxConjunto = QtWidgets.QPushButton(self.page_2)
        self.pushButton_calcularDemandaMaxConjunto.setGeometry(QtCore.QRect(780, 360, 161, 51))
        self.pushButton_calcularDemandaMaxConjunto.setStyleSheet("QPushButton {\n"
"    background-color: #FFA726; \n"
"    border-radius: 10px;\n"
"    font-size: 20px; \n"
"}\n"
"QPushButton:hover {\n"
"    background-color: #FF9800;\n"
"}")
        self.pushButton_calcularDemandaMaxConjunto.setObjectName("pushButton_calcularDemandaMaxConjunto")
        self.pushButton_volver = QtWidgets.QPushButton(self.page_2)
        self.pushButton_volver.setGeometry(QtCore.QRect(930, 770, 161, 51))
        self.pushButton_volver.setStyleSheet("QPushButton {\n"
"    background-color: #c7bb29; \n"
"    border-radius: 10px;\n"
"    font-size: 20px; \n"
"}\n"
"QPushButton:hover {\n"
"    background-color: #ece272;\n"
"    color: #626260;\n"
"}")
        self.pushButton_volver.setObjectName("pushButton_volver")
        self.stackedWidget.addWidget(self.page_2)
        self.page_3 = QtWidgets.QWidget()
        self.page_3.setObjectName("page_3")
        self.label_tituloCalculoCable = QtWidgets.QLabel(self.page_3)
        self.label_tituloCalculoCable.setGeometry(QtCore.QRect(0, 50, 1121, 61))
        self.label_tituloCalculoCable.setStyleSheet("QLabel {\n"
"    font-size: 40px;\n"
"    color: #FFA726;\n"
"}")
        self.label_tituloCalculoCable.setAlignment(QtCore.Qt.AlignCenter)
        self.label_tituloCalculoCable.setObjectName("label_tituloCalculoCable")
        self.lineEdit_longitudCable = QtWidgets.QLineEdit(self.page_3)
        self.lineEdit_longitudCable.setGeometry(QtCore.QRect(350, 180, 91, 31))
        self.lineEdit_longitudCable.setStyleSheet("QLineEdit {\n"
"    border: none;\n"
"    border-bottom: 2px solid white;\n"
"    background-color: transparent;\n"
"    font-size: 23px;\n"
"}\n"
"QLineEdit:hover {\n"
"    background-color: #4d4d4d;\n"
"}")
        self.lineEdit_longitudCable.setText("")
        self.lineEdit_longitudCable.setAlignment(QtCore.Qt.AlignCenter)
        self.lineEdit_longitudCable.setObjectName("lineEdit_longitudCable")
        self.lineEdit_temperatura = QtWidgets.QLineEdit(self.page_3)
        self.lineEdit_temperatura.setGeometry(QtCore.QRect(260, 260, 91, 31))
        self.lineEdit_temperatura.setStyleSheet("QLineEdit {\n"
"    border: none;\n"
"    border-bottom: 2px solid white;\n"
"    background-color: transparent;\n"
"    font-size: 23px;\n"
"}\n"
"QLineEdit:hover {\n"
"    background-color: #4d4d4d;\n"
"}")
        self.lineEdit_temperatura.setText("")
        self.lineEdit_temperatura.setAlignment(QtCore.Qt.AlignCenter)
        self.lineEdit_temperatura.setObjectName("lineEdit_temperatura")
        self.label_criterioCaidaConduccion = QtWidgets.QLabel(self.page_3)
        self.label_criterioCaidaConduccion.setGeometry(QtCore.QRect(420, 700, 151, 31))
        self.label_criterioCaidaConduccion.setStyleSheet("QLabel {\n"
"    font-size: 20px;\n"
"}")
        self.label_criterioCaidaConduccion.setText("")
        self.label_criterioCaidaConduccion.setObjectName("label_criterioCaidaConduccion")
        self.label_temperatura = QtWidgets.QLabel(self.page_3)
        self.label_temperatura.setGeometry(QtCore.QRect(80, 260, 171, 31))
        self.label_temperatura.setStyleSheet("QLabel {\n"
"    font-size: 20px;\n"
"}")
        self.label_temperatura.setObjectName("label_temperatura")
        self.label_tipoSistema = QtWidgets.QLabel(self.page_3)
        self.label_tipoSistema.setGeometry(QtCore.QRect(630, 200, 181, 31))
        self.label_tipoSistema.setStyleSheet("QLabel {\n"
"    font-size: 20px;\n"
"}")
        self.label_tipoSistema.setObjectName("label_tipoSistema")
        self.label_seccionCable = QtWidgets.QLabel(self.page_3)
        self.label_seccionCable.setGeometry(QtCore.QRect(850, 660, 151, 31))
        self.label_seccionCable.setStyleSheet("QLabel {\n"
"    font-size: 20px;\n"
"}")
        self.label_seccionCable.setText("")
        self.label_seccionCable.setObjectName("label_seccionCable")
        self.label_titulo_criterioCaidaConduccion = QtWidgets.QLabel(self.page_3)
        self.label_titulo_criterioCaidaConduccion.setGeometry(QtCore.QRect(80, 700, 331, 31))
        self.label_titulo_criterioCaidaConduccion.setStyleSheet("QLabel {\n"
"    font-size: 20px;\n"
"    color: #FFD54F;\n"
"    font-weight: bold;\n"
"}")
        self.label_titulo_criterioCaidaConduccion.setObjectName("label_titulo_criterioCaidaConduccion")
        self.label_caidaTension = QtWidgets.QLabel(self.page_3)
        self.label_caidaTension.setGeometry(QtCore.QRect(630, 420, 181, 31))
        self.label_caidaTension.setStyleSheet("QLabel {\n"
"    font-size: 20px;\n"
"}")
        self.label_caidaTension.setObjectName("label_caidaTension")
        self.label_longitudCable = QtWidgets.QLabel(self.page_3)
        self.label_longitudCable.setGeometry(QtCore.QRect(80, 180, 271, 31))
        self.label_longitudCable.setStyleSheet("QLabel {\n"
"    font-size: 20px;\n"
"}")
        self.label_longitudCable.setObjectName("label_longitudCable")
        self.label_titulo_seccionCable = QtWidgets.QLabel(self.page_3)
        self.label_titulo_seccionCable.setGeometry(QtCore.QRect(650, 660, 191, 31))
        self.label_titulo_seccionCable.setStyleSheet("QLabel {\n"
"    font-size: 20px;\n"
"    color: #FFD54F;\n"
"    font-weight: bold;\n"
"}")
        self.label_titulo_seccionCable.setObjectName("label_titulo_seccionCable")
        self.label_aislamientoConductor = QtWidgets.QLabel(self.page_3)
        self.label_aislamientoConductor.setGeometry(QtCore.QRect(630, 300, 261, 31))
        self.label_aislamientoConductor.setStyleSheet("QLabel {\n"
"    font-size: 20px;\n"
"}")
        self.label_aislamientoConductor.setObjectName("label_aislamientoConductor")
        self.label_titulo_criterioCaidaTension = QtWidgets.QLabel(self.page_3)
        self.label_titulo_criterioCaidaTension.setGeometry(QtCore.QRect(80, 640, 291, 31))
        self.label_titulo_criterioCaidaTension.setStyleSheet("QLabel {\n"
"    font-size: 20px;\n"
"    color: #FFD54F;\n"
"    font-weight: bold;\n"
"}")
        self.label_titulo_criterioCaidaTension.setObjectName("label_titulo_criterioCaidaTension")
        self.label_criterioCaidaTension = QtWidgets.QLabel(self.page_3)
        self.label_criterioCaidaTension.setGeometry(QtCore.QRect(380, 640, 151, 31))
        self.label_criterioCaidaTension.setStyleSheet("QLabel {\n"
"    font-size: 20px;\n"
"}")
        self.label_criterioCaidaTension.setText("")
        self.label_criterioCaidaTension.setObjectName("label_criterioCaidaTension")
        self.pushButton_calcularSeccionCable = QtWidgets.QPushButton(self.page_3)
        self.pushButton_calcularSeccionCable.setGeometry(QtCore.QRect(450, 540, 161, 51))
        self.pushButton_calcularSeccionCable.setStyleSheet("QPushButton {\n"
"    background-color: #FFA726; \n"
"    border-radius: 10px;\n"
"    font-size: 20px; \n"
"}\n"
"QPushButton:hover {\n"
"    background-color: #FF9800;\n"
"}")
        self.pushButton_calcularSeccionCable.setObjectName("pushButton_calcularSeccionCable")
        self.pushButton_volver_2 = QtWidgets.QPushButton(self.page_3)
        self.pushButton_volver_2.setGeometry(QtCore.QRect(930, 770, 161, 51))
        self.pushButton_volver_2.setStyleSheet("QPushButton {\n"
"    background-color: #c7bb29; \n"
"    border-radius: 10px;\n"
"    font-size: 20px; \n"
"}\n"
"QPushButton:hover {\n"
"    background-color: #ece272;\n"
"    color: #626260;\n"
"}")
        self.pushButton_volver_2.setObjectName("pushButton_volver_2")
        self.groupBox_tipoSistema = QtWidgets.QGroupBox(self.page_3)
        self.groupBox_tipoSistema.setGeometry(QtCore.QRect(800, 180, 151, 71))
        self.groupBox_tipoSistema.setStyleSheet("QGroupBox {\n"
"    border: none;\n"
"}\n"
"")
        self.groupBox_tipoSistema.setTitle("")
        self.groupBox_tipoSistema.setObjectName("groupBox_tipoSistema")
        self.radioButton_monofasico = QtWidgets.QRadioButton(self.groupBox_tipoSistema)
        self.radioButton_monofasico.setGeometry(QtCore.QRect(10, 10, 131, 20))
        self.radioButton_monofasico.setStyleSheet("QRadioButton {\n"
"    font-size: 18px;\n"
"}")
        self.radioButton_monofasico.setObjectName("radioButton_monofasico")
        self.radioButton_trifasico = QtWidgets.QRadioButton(self.groupBox_tipoSistema)
        self.radioButton_trifasico.setGeometry(QtCore.QRect(10, 40, 95, 20))
        self.radioButton_trifasico.setStyleSheet("QRadioButton {\n"
"    font-size: 18px;\n"
"}")
        self.radioButton_trifasico.setObjectName("radioButton_trifasico")
        self.groupBox_aislamientoConductor = QtWidgets.QGroupBox(self.page_3)
        self.groupBox_aislamientoConductor.setGeometry(QtCore.QRect(890, 270, 121, 101))
        self.groupBox_aislamientoConductor.setStyleSheet("QGroupBox {\n"
"    border: none;\n"
"}\n"
"")
        self.groupBox_aislamientoConductor.setTitle("")
        self.groupBox_aislamientoConductor.setObjectName("groupBox_aislamientoConductor")
        self.radioButton_PVC = QtWidgets.QRadioButton(self.groupBox_aislamientoConductor)
        self.radioButton_PVC.setGeometry(QtCore.QRect(10, 10, 81, 20))
        self.radioButton_PVC.setStyleSheet("QRadioButton {\n"
"    font-size: 18px;\n"
"}")
        self.radioButton_PVC.setObjectName("radioButton_PVC")
        self.radioButton_EPR = QtWidgets.QRadioButton(self.groupBox_aislamientoConductor)
        self.radioButton_EPR.setGeometry(QtCore.QRect(10, 40, 81, 20))
        self.radioButton_EPR.setStyleSheet("QRadioButton {\n"
"    font-size: 18px;\n"
"}")
        self.radioButton_EPR.setObjectName("radioButton_EPR")
        self.radioButton_XLPE = QtWidgets.QRadioButton(self.groupBox_aislamientoConductor)
        self.radioButton_XLPE.setGeometry(QtCore.QRect(10, 70, 81, 20))
        self.radioButton_XLPE.setStyleSheet("QRadioButton {\n"
"    font-size: 18px;\n"
"}")
        self.radioButton_XLPE.setObjectName("radioButton_XLPE")
        self.groupBox_caidaTension = QtWidgets.QGroupBox(self.page_3)
        self.groupBox_caidaTension.setGeometry(QtCore.QRect(800, 390, 191, 101))
        self.groupBox_caidaTension.setStyleSheet("QGroupBox {\n"
"    border: none;\n"
"}\n"
"")
        self.groupBox_caidaTension.setTitle("")
        self.groupBox_caidaTension.setObjectName("groupBox_caidaTension")
        self.radioButton_alimentador = QtWidgets.QRadioButton(self.groupBox_caidaTension)
        self.radioButton_alimentador.setGeometry(QtCore.QRect(10, 10, 141, 20))
        self.radioButton_alimentador.setStyleSheet("QRadioButton {\n"
"    font-size: 18px;\n"
"}")
        self.radioButton_alimentador.setObjectName("radioButton_alimentador")
        self.radioButton_circuitoDerivado = QtWidgets.QRadioButton(self.groupBox_caidaTension)
        self.radioButton_circuitoDerivado.setGeometry(QtCore.QRect(10, 40, 171, 20))
        self.radioButton_circuitoDerivado.setStyleSheet("QRadioButton {\n"
"    font-size: 18px;\n"
"}")
        self.radioButton_circuitoDerivado.setObjectName("radioButton_circuitoDerivado")
        self.radioButton_ninguno = QtWidgets.QRadioButton(self.groupBox_caidaTension)
        self.radioButton_ninguno.setGeometry(QtCore.QRect(10, 70, 111, 20))
        self.radioButton_ninguno.setStyleSheet("QRadioButton {\n"
"    font-size: 18px;\n"
"}")
        self.radioButton_ninguno.setObjectName("radioButton_ninguno")
        self.lineEdit_tubosVerticales = QtWidgets.QLineEdit(self.page_3)
        self.lineEdit_tubosVerticales.setGeometry(QtCore.QRect(380, 350, 91, 31))
        self.lineEdit_tubosVerticales.setStyleSheet("QLineEdit {\n"
"    border: none;\n"
"    border-bottom: 2px solid white;\n"
"    background-color: transparent;\n"
"    font-size: 23px;\n"
"}\n"
"QLineEdit:hover {\n"
"    background-color: #4d4d4d;\n"
"}")
        self.lineEdit_tubosVerticales.setText("")
        self.lineEdit_tubosVerticales.setAlignment(QtCore.Qt.AlignCenter)
        self.lineEdit_tubosVerticales.setObjectName("lineEdit_tubosVerticales")
        self.label_tubosVerticales = QtWidgets.QLabel(self.page_3)
        self.label_tubosVerticales.setGeometry(QtCore.QRect(80, 350, 261, 31))
        self.label_tubosVerticales.setStyleSheet("QLabel {\n"
"    font-size: 20px;\n"
"}")
        self.label_tubosVerticales.setObjectName("label_tubosVerticales")
        self.label_tubosHorizontales = QtWidgets.QLabel(self.page_3)
        self.label_tubosHorizontales.setGeometry(QtCore.QRect(80, 420, 291, 31))
        self.label_tubosHorizontales.setStyleSheet("QLabel {\n"
"    font-size: 20px;\n"
"}")
        self.label_tubosHorizontales.setObjectName("label_tubosHorizontales")
        self.lineEdit_tubosHorizontales = QtWidgets.QLineEdit(self.page_3)
        self.lineEdit_tubosHorizontales.setGeometry(QtCore.QRect(380, 420, 91, 31))
        self.lineEdit_tubosHorizontales.setStyleSheet("QLineEdit {\n"
"    border: none;\n"
"    border-bottom: 2px solid white;\n"
"    background-color: transparent;\n"
"    font-size: 23px;\n"
"}\n"
"QLineEdit:hover {\n"
"    background-color: #4d4d4d;\n"
"}")
        self.lineEdit_tubosHorizontales.setText("")
        self.lineEdit_tubosHorizontales.setAlignment(QtCore.Qt.AlignCenter)
        self.lineEdit_tubosHorizontales.setObjectName("lineEdit_tubosHorizontales")
        self.stackedWidget.addWidget(self.page_3)
        MainWindow.setCentralWidget(self.centralwidget)

        self.retranslateUi(MainWindow)
        self.stackedWidget.setCurrentIndex(2)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.label_titulo.setText(_translate("MainWindow", "DEMANDA MÁXIMA DE UNA CASA"))
        self.tableWidget.setSortingEnabled(False)
        __sortingEnabled = self.tableWidget.isSortingEnabled()
        self.tableWidget.setSortingEnabled(False)
        item = self.tableWidget.item(0, 0)
        item.setText(_translate("MainWindow", "NOMBRE"))
        item = self.tableWidget.item(0, 1)
        item.setText(_translate("MainWindow", "ANCHO"))
        item = self.tableWidget.item(0, 2)
        item.setText(_translate("MainWindow", "LARGO"))
        item = self.tableWidget.item(0, 3)
        item.setText(_translate("MainWindow", "TOMACORRIENTES"))
        item = self.tableWidget.item(0, 4)
        item.setText(_translate("MainWindow", "PUNTOS DE ILUMINACIÓN"))
        self.tableWidget.setSortingEnabled(__sortingEnabled)
        self.label_enunciado.setText(_translate("MainWindow", "Ingrese las habitaciones o espacios de la casa:"))
        self.label_titulo2.setText(_translate("MainWindow", "Potencia instalada en iluminación:"))
        self.label_titulo3.setText(_translate("MainWindow", "Potencia instalada en las tomas:"))
        self.pushButton_calcularDemandaCasa.setText(_translate("MainWindow", "CALCULAR DEMANDA"))
        self.pushButton_calcularDemandaConjunto.setText(_translate("MainWindow", "CALCULAR DEMANDA DEL CONJUNTO"))
        self.pushButton_calcularCable.setText(_translate("MainWindow", "CALCULAR CABLE"))
        self.label_enunciado_2.setText(_translate("MainWindow", "Ingrese los datos de cada espacio de la casa:"))
        self.pushButton_generarTabla.setText(_translate("MainWindow", "Enviar"))
        self.label_anchoCasa.setText(_translate("MainWindow", "Ancho de la casa:"))
        self.label_largoCasa.setText(_translate("MainWindow", "Largo de la casa:"))
        self.label_numeroAires.setText(_translate("MainWindow", "Número de aires acondicionados:"))
        self.label_titulo4.setText(_translate("MainWindow", "Potencia en fuerza:"))
        self.label_titulo5.setText(_translate("MainWindow", "Demanda máxima:"))
        self.label_potenciaAire.setText(_translate("MainWindow", "Potencia consumida de cada aire:"))
        self.label_tituloDemandaConjunto.setText(_translate("MainWindow", "DEMANDA MÁXIMA DE UN CONJUNTO"))
        self.label_numeroCasas.setText(_translate("MainWindow", "Número de casas del conjunto:"))
        self.label_numeroLocales.setText(_translate("MainWindow", "Número de locales del conjunto:"))
        self.label_demandaMaxLocal.setText(_translate("MainWindow", "Demanda máxima de cada local (W):"))
        self.label_demandaMaxServicios.setText(_translate("MainWindow", "Demanda máxima de los servicios generales (W):"))
        self.label_titulo_demandaMaxConjunto.setText(_translate("MainWindow", "Demanda máxima del conjunto:"))
        self.pushButton_calcularDemandaMaxConjunto.setText(_translate("MainWindow", "CALCULAR"))
        self.pushButton_volver.setText(_translate("MainWindow", "VOLVER"))
        self.label_tituloCalculoCable.setText(_translate("MainWindow", "CÁLCULO DE CABLE DE LA CASA"))
        self.label_temperatura.setText(_translate("MainWindow", "Temperatura (°C):"))
        self.label_tipoSistema.setText(_translate("MainWindow", "Tipo de sistema:"))
        self.label_titulo_criterioCaidaConduccion.setText(_translate("MainWindow", "Criterio de caída de conducción:"))
        self.label_caidaTension.setText(_translate("MainWindow", "Caída de tensión:"))
        self.label_longitudCable.setText(_translate("MainWindow", "Longitud del cable (metros):"))
        self.label_titulo_seccionCable.setText(_translate("MainWindow", "Sección del cable:"))
        self.label_aislamientoConductor.setText(_translate("MainWindow", "Aislamiento del conductor:"))
        self.label_titulo_criterioCaidaTension.setText(_translate("MainWindow", "Criterio de caída de tensión:"))
        self.pushButton_calcularSeccionCable.setText(_translate("MainWindow", "CALCULAR"))
        self.pushButton_volver_2.setText(_translate("MainWindow", "VOLVER"))
        self.radioButton_monofasico.setText(_translate("MainWindow", "Monofásico"))
        self.radioButton_trifasico.setText(_translate("MainWindow", "Trifásico"))
        self.radioButton_PVC.setText(_translate("MainWindow", "PVC"))
        self.radioButton_EPR.setText(_translate("MainWindow", "EPR"))
        self.radioButton_XLPE.setText(_translate("MainWindow", "XLPE"))
        self.radioButton_alimentador.setText(_translate("MainWindow", "Alimentador"))
        self.radioButton_circuitoDerivado.setText(_translate("MainWindow", "Circuito derivado"))
        self.radioButton_ninguno.setText(_translate("MainWindow", "Ninguno"))
        self.label_tubosVerticales.setText(_translate("MainWindow", "Número de tubos en vertical:"))
        self.label_tubosHorizontales.setText(_translate("MainWindow", "Número de tubos en horizontal:"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())
